In [1]:
import numpy as np

In [2]:
dataset = np.arange(48).reshape(6,8)

In [3]:
dataset

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

# Splitting

In [4]:
np.hsplit(dataset, 2)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35],
        [40, 41, 42, 43]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39],
        [44, 45, 46, 47]])]

In [5]:
np.split(dataset,2, axis=1)

[array([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11],
        [16, 17, 18, 19],
        [24, 25, 26, 27],
        [32, 33, 34, 35],
        [40, 41, 42, 43]]),
 array([[ 4,  5,  6,  7],
        [12, 13, 14, 15],
        [20, 21, 22, 23],
        [28, 29, 30, 31],
        [36, 37, 38, 39],
        [44, 45, 46, 47]])]

In [6]:
np.vsplit(dataset, 2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]])]

In [7]:
np.split(dataset,2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47]])]

In [8]:
for data in np.nditer(dataset):
    print(data)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47


In [9]:
for data in dataset:
    print(data)

[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15]
[16 17 18 19 20 21 22 23]
[24 25 26 27 28 29 30 31]
[32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47]


In [10]:
for data in dataset:
    for value in data:
        print(value)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47


# Filtering, Sorting, Combining and reshaping

In [11]:
dataset

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [12]:
np.extract((dataset < 10), dataset)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.extract((dataset < 10)|(dataset > 40), dataset)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 41, 42, 43, 44, 45, 46, 47])

In [14]:
np.where(dataset < 10)

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1], dtype=int64))

In [15]:
np.where((dataset < 10) | (dataset > 40))

(array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 5, 5, 5, 5, 5, 5, 5], dtype=int64),
 array([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 1, 2, 3, 4, 5, 6, 7], dtype=int64))

## Sorting

In [19]:
from numpy import random
x = random.randint(100, size=(6,8))
x

array([[ 3, 96, 19, 95, 33, 67, 27, 45],
       [ 7, 58, 36, 96, 46, 30, 37,  8],
       [36, 61, 11, 10, 56, 52, 50, 37],
       [17,  4, 88, 20, 29, 71, 72, 67],
       [60, 89, 28,  0, 66, 20, 20, 51],
       [18, 47, 24, 27, 22, 29, 49, 94]])

In [21]:
np.sort(x)

array([[ 3, 19, 27, 33, 45, 67, 95, 96],
       [ 7,  8, 30, 36, 37, 46, 58, 96],
       [10, 11, 36, 37, 50, 52, 56, 61],
       [ 4, 17, 20, 29, 67, 71, 72, 88],
       [ 0, 20, 20, 28, 51, 60, 66, 89],
       [18, 22, 24, 27, 29, 47, 49, 94]])

In [22]:
np.sort(x, axis=1)

array([[ 3, 19, 27, 33, 45, 67, 95, 96],
       [ 7,  8, 30, 36, 37, 46, 58, 96],
       [10, 11, 36, 37, 50, 52, 56, 61],
       [ 4, 17, 20, 29, 67, 71, 72, 88],
       [ 0, 20, 20, 28, 51, 60, 66, 89],
       [18, 22, 24, 27, 29, 47, 49, 94]])

In [23]:
np.sort(x, axis=0)

array([[ 3,  4, 11,  0, 22, 20, 20,  8],
       [ 7, 47, 19, 10, 29, 29, 27, 37],
       [17, 58, 24, 20, 33, 30, 37, 45],
       [18, 61, 28, 27, 46, 52, 49, 51],
       [36, 89, 36, 95, 56, 67, 50, 67],
       [60, 96, 88, 96, 66, 71, 72, 94]])

In [26]:
dataset = np.arange(9).reshape(3,3)
dataset

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Combining and reshaping