In [2]:
import numpy as np

In [5]:
dataset = np.arange(9)
dataset

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
dataset = dataset.reshape(3,3)

In [12]:
np.mean(dataset)

4.0

In [13]:
np.mean(dataset, axis=0)

array([3., 4., 5.])

In [15]:
np.mean(dataset, axis=1)

array([1., 4., 7.])

In [20]:
from scipy import stats as st

In [21]:
st.mode(dataset, axis = 0)

ModeResult(mode=array([[0, 1, 2]]), count=array([[1, 1, 1]]))

In [22]:
st.mode(dataset, axis = 1)

ModeResult(mode=array([[0],
       [3],
       [6]]), count=array([[1],
       [1],
       [1]]))

## Variance and Standard deviation

In [23]:
a = np.arange(start = 1, stop = 5, step = 1)

In [24]:
a

array([1, 2, 3, 4])

In [25]:
a = a.reshape(2,2)

In [26]:
a

array([[1, 2],
       [3, 4]])

In [28]:
np.mean(a)

2.5

In [29]:
np.var(a)

1.25

In [36]:
# standard deviation equals to variance when squared
np.std(a)**2

1.2500000000000002

In [30]:
np.mean(a, axis = 0)

array([2., 3.])

In [31]:
np.var(a, axis = 0)

array([1., 1.])

In [32]:
np.mean(a, axis = 1)

array([1.5, 3.5])

In [33]:
np.var(a, axis = 1)

array([0.25, 0.25])