In [1]:
import numpy as np

In [19]:
m = (np.arange(12)+1).reshape(3,4)

In [20]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
m[:2,:2]

array([[1, 2],
       [5, 6]])

In [22]:
m[-2:,-2:]

array([[ 7,  8],
       [11, 12]])

In [23]:
m[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [24]:
m.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])