In [2]:
import numpy as np

In [3]:
m = (np.arange(12)+1).reshape(3,4)

In [4]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
m[:2,:2]

array([[1, 2],
       [5, 6]])

In [22]:
m[-2:,-2:]

array([[ 7,  8],
       [11, 12]])

In [23]:
m[:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [5]:
m.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [6]:
max(m)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [7]:
import pandas as pd
import numpy as np
s = pd.Series(np.random.randn(4))
print(s.ndim)

1


In [9]:
a = np.array([[1, 2 ],[3,4]])
b= np.array([[5,6],[7,8]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [11]:
b

array([[5, 6],
       [7, 8]])

In [17]:
np.vstack([a,b])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
max(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()